# Generated by Django 5.0.1 on 2024-01-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
